### PR TITLE
Headers and Authorization

### PR DESCRIPTION
**Pull request by mattiasnordqvist**
Added possibility to add headers through parameters.
Can be done on dynamically on parameter and transformer pipeline level,
or statically on method or interface-level
Added specialized header for the Authorization header.

### CODE REVIEW

**Comment by mattiasnordqvist** [comment]
How about adding a new ParameterType for Headers?
Documented here https://github.com/mattiasnordqvist/Web-Anchor/wiki/Authentication
What do you think? Should we add this?

**Comment by carl-berg** [comment]
I like it. I sort of feel like the attribute versions are more for demo purposes and are not as likely to be used in actual implementations where you might want to vary the Authorization value per user (which I probably would implement using a parameter list transformer).

**Comment by mattiasnordqvist** [comment]
Yep. There is an AddHeaderTransformer provided already. Last thing in the doc

**Comment by mattiasnordqvist** [comment]
Released in v2.1.35

**Pull request merged**
